### ISSUE TITLE
Product Service #1 - Query Products

### ISSUE THREAD

**Issue by freemanpivo** [freemanpivo/coffee-station#7]
**tasks:**
- [x] Configure basic app template (kotlin)
- [x] Add missing dependencies (awsjdk, validations)

**features:**
- [x] **FEATURE:** query all products
- [x] **FEATURE:** query products by name
- [x] **FEATURE:** query products by preparation
- [x] **FEATURE:** query products by id

**nonfunctional:**
- [ ] Use Log standardization
- [ ] Send telemetry messages to `prometheus`
- [ ] Cache Data with Spring Cache
- [ ] Handle error HTTP codes as well `ProblemDetails` response
- [x] Use standard success payload
